server:
  port: ${PORT:2222}
  servlet:
    context-path: /order

spring:
  application:
    name: containerized-orders
  logstash:
    server: logstash
    port: 5000
  sleuth:
    traceId128: true
    supportsJoin: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
logging:
  pattern:
    level: "trace_id=%X{traceId:-} span_id=%X{spanId:-} trace_flags=%X{trace_flags} %p"
  level:
    com.tanerdiler.microservice.order: DEBUG
    org.springframework: WARN
    org.hibernate: WARN

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/

ribbon:
  eureka:
    enabled: true
